# Generated by Django 5.2.6 on 2025-10-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='title',
            field=models.CharField(choices=[('backend', 'Back-end Developer'), ('frontend', 'Front-end Developer'), ('devops', 'Devops Developer'), ('uiux', 'UIUX Developer'), ('pm', 'Project Manager')], max_length=50),
        ),
    ]
