# Generated by Django 5.2.6 on 2025-10-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_candidate_degree_remove_candidate_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='title',
            field=models.CharField(choices=[('backend', 'Back-end Developer'), ('frontend', 'Front-end Developer'), ('devops', 'DevOps Engineer'), ('uiux', 'UI/UX Designer'), ('pm', 'Project Manager')], max_length=50),
        ),
    ]
