# Generated by Django 5.2.6 on 2025-10-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_jobposition_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='group',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
